---
title: "R Notebook"
output: Aula 3 - Deep Learning
---
#Pacotes
```{r}
library("rattle")
library("rnn")
library("ggplot2")
```

#Dados = Weather AUS
```{r}
data(weatherAUS)
#View(weatherAUS)
#extrair somente colunas 1 and 14  e primeiras 3040 linhas (Albury location)
data <- weatherAUS[1:3040,14:15]
summary(data)
```

#Pre-processamento
```{r}

data_cleaned <- na.omit(data)
data_used=data_cleaned[1:3000,]
x=data_used[,1]
y=data_used[,2]

Yscaled = (y - min(y)) / (max(y) - min(y))
Xscaled = (x - min(x)) / (max(x) - min(x))

y <- Yscaled
x <- Xscaled

x <- as.matrix(x)
y <- as.matrix(y)

X <- matrix(x, nrow = 30)
Y <- matrix(y, nrow = 30)

#train test split
train=1:80
test=81:100
```

#modelo
```{r}
set.seed(12)
model <- trainr(Y = Y[,train],
                X = X[,train],
                learningrate = 0.01,
                hidden_dim = 15,
                network_type = "rnn",
                numepochs = 100)

model$error
#poucas épocas?
plot(colMeans(model$error),type='l',xlab='epoch',ylab='errors')
```

#predição
```{r}
Yp <- predictr(model, X[,test])

#Percentual de variação em uma variável explicada por outra
#por enquanto: entenda que é um percentual de variação explicada
rsq <- function(y_actual,y_predict)
{
  cor(y_actual,y_predict)^2
}


Ytest <- matrix(Y[,test], nrow = 1)
Ytest <- t(Ytest)
Ypredicted <- matrix(Yp, nrow = 1)
Ypredicted <- t(Ypredicted)

result_data <- data.frame(Ytest)
result_data$Ypredicted <- Ypredicted     

rsq(result_data$Ytest,result_data$Ypredicted)

mean(result_data$Ytest)
mean(result_data$Ypredicted)
```

#grafico
```{r}
plot(as.vector(t(result_data$Ytest)), col = 'red', type='l',
main = "Actual vs Predicted Humidity: testing set",
ylab = "Y,Yp")
lines(as.vector(t(Yp)), type = 'l', col = 'black')
legend("bottomright", c("Predicted", "Actual"),
col = c("red","black"),
lty = c(1,1), lwd = c(1,1))
```

#EXERCICIO 1
```{r}
library("rnn")
library("dplyr")

data <- read.csv("PETR4.SA.csv")

#Inverter a ordem das ações para pegar da última para a ´primeira
data <-data[order(data$Date, decreasing = TRUE),]

fechamento <- data$Close

fechamento_anterior <- lead(fechamento,n=1L)

data_analise <- data.frame(fechamento)
data_analise$fechamento_anterior <- fechamento_anterior


summary(data_analise)

#exclui NA
data_analise <- data_analise[1:248,]


x <- data_analise[,2]
y <- data_analise[,1]


X <- matrix(x, nrow = 31)
Y <- matrix(y, nrow = 31)


Yscaled <- (Y - min(Y)) / (max(Y) - min(Y))
Xscaled <- (X - min(X)) / (max(X) - min(X))
Y <- Yscaled
X <- Xscaled


train=1:6
test=7:8

set.seed(12)
model <- trainr(Y = Y[,train],
                X = X[,train],
                learningrate = 0.05,
                hidden_dim = 20,
                numepochs = 1000,
                network_type = "rnn"
                )


#no conjunto de treinamento
Ytrain <- t(matrix(predictr(model, X[,train]),nrow=1))
Yreal <- t(matrix(Y[,train],nrow=1))

#Percentual de variação em uma variável explicada por outra
rsq <- function(y_actual,y_predict){
  cor(y_actual,y_predict)^2
}

rsq(Yreal,Ytrain)

plot(Ytrain, type = "l", col = "darkred")
lines(Yreal, col = "darkblue", type = "l")

#no conjunto de teste
Ytest=matrix(Y[,test], nrow = 1)
Ytest = t(Ytest)
Yp <- predictr(model, Y[,test])
Ypredicted=matrix(Yp, nrow = 1)
Ypredicted=t(Ypredicted)

result_data <- data.frame(Ytest)
result_data$Ypredicted <- Ypredicted     

rsq(result_data$Ytest,result_data$Ypredicted)

mean(result_data$Ytest)
mean(result_data$Ypredicted)
```









